# Generated by Django 5.1.2 on 2024-10-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('unique_hash', models.CharField(max_length=20, unique=True)),
                ('tx_hash', models.CharField(max_length=66)),
                ('media_url', models.URLField()),
                ('owner', models.CharField(max_length=42)),
            ],
        ),
    ]
